import math
print('a:',(3+4)*(5))
n= float(input("Enter the value of n: "))
print('b:',n*(n-1)/2)
r1=float(input("Enter the value of r1: "))
print('c:',4*math.pi*r1**2)
a=float(input("Enter the value of a: "))
b=float(input("Enter the value of b: "))
r2=float(input("Enter the value of r2: "))
print('d:',math.sqrt(r2*(math.cos(a)**2) + r2*(math.sin(b)**2)))
x1=float(input("Enter the value of x1: "))
x2=float(input("Enter the value of x2: "))
y1=float(input("Enter the value of y1: "))
y2=float(input("Enter the value of y2: "))
print('e:',(y2-y1)/(x2-x1))

